vimc-7192 - alter table coverage - add percent_gavi_support
vimc/montagu-db pull request #171
Opened 2023-08-21 12:04 UTC by xiangli313

Youtrack: 
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-7192/db-migration-create-percentgavisupport

Task:
Gavi requested adding % of gavi_support in future data sets. Hence, we record this % in coverage table.

2023-08-21 12:21 UTC, richfitz requested changes
Unless there's a good reason not to, please use the simpler type.

Note that there will be a delay on getting this deployed as we are in the process of moving servers around

2023-08-21 12:21 UTC, richfitz commented on migrations/sql/V2023.08.21.1254__AddPercentGaviSupportToCoverage.sql
> +    ADD COLUMN percent_gavi_support DECIMAL DEFAULT NULL
```suggestion
    ADD COLUMN percent_gavi_support DOUBLE PRECISION DEFAULT NULL
```

The "decimal" type has much worse performance. I see we still have a bunch of those around though. It's not super obvious which is which typically!

https://www.postgresql.org/docs/current/datatype-numeric.html

2023-08-21 12:21 UTC, richfitz requested changes
Unless there's a good reason not to, please use the simpler type.

Note that there will be a delay on getting this deployed as we are in the process of moving servers around

2023-08-21 14:00 UTC, xiangli313 commented
Thanks, Rick. I will give you a reminder after the process of moving servers.

2024-03-20 10:13 UTC, richfitz requested changes

2024-03-20 10:13 UTC, richfitz commented on migrations/sql/V2023.08.21.1254__AddPercentGaviSupportToCoverage.sql
when we merge this, update the filename to be later than this, as I've set other migrations to run first

2024-03-20 10:42 UTC, richfitz approved these changes

2024-03-20 10:43 UTC, merged