vimc-7314: add new burden outcome: yll_cwyx for MenA
vimc/montagu-db pull request #173
Opened 2024-03-13 14:59 UTC by xiangli313

2024-03-13 17:46 UTC, weshinsley requested changes
One typo! I am not sure how we delpoy migration (does this definitely need to be one, and not a montagu-import ? I am not sure of that bit either!)

2024-03-13 17:46 UTC, weshinsley commented on migrations/sql/V2024.03.13.1457__AddBurdenOutcome.sql
> +INSERT INTO burden_outcome (code, name, proportion) VALUES ('yll_cwyx', 'Yeas of life lost attributable to Meningitis serogroups C,W,X and Y', FALSE);
```suggestion
INSERT INTO burden_outcome (code, name, proportion) VALUES ('yll_cwyx', 'Years of life lost attributable to Meningitis serogroups C,W,X and Y', FALSE);
```

2024-03-15 09:54 UTC, xiangli313 commented
Hi @weshinsley, thanks for looking into this PR. According to my previous experience, burden_outcome is an enum table, hence any new rows need to be added via a migration script in this repo. It is fine to wait until Rich is back for this.

2024-03-20 10:15 UTC, richfitz approved these changes

2024-03-20 10:16 UTC, weshinsley approved these changes

2024-03-20 10:16 UTC, merged